### ISSUE TITLE
Can't focus Input fields

### ISSUE THREAD

**Issue by iseries** [mdbootstrap/Black-Friday-2025#3] opened 2020-06-25 17:45 UTC
I can't focus Input fields in mobile device.

Phone: Google Pixel 4 XL
Browser: Google Chrome

**Comment by smolenski-mikolaj** [comment] 2020-06-25 18:05
Could you share full code of Your Input Field? I can't reproduce the issue for the standard outline form.

**Comment by iseries** [comment] 2020-06-25 18:36
I have this problem in the official online Demo. I'll try to make a Video on my phone.

**Comment by iseries** [comment] 2020-06-25 18:40
See video

**Comment by iseries** [comment] 2020-06-25 18:48
See video: http://eventuu.com/Video_2020-06-25_at_20.41.07.mp4

Edit: Ok can reproduce this on firefox, too. I thought about a keyboard bug but i can focus normal input fields:
http://eventuu.com/Video_2020-06-25_at_20.59.26.mp4

**Comment by pau1phi11ips** [comment] 2020-06-26 06:21
This happens on my phone too, keyboard flashes up and then disappears.

**Comment by hitrop** [comment] 2020-06-26 08:00
Also is it possible to increase the default vertical padding in input fields? It seems a bit cramped up.

**Comment by smolenski-mikolaj** [comment] 2020-07-03 08:25
> Also is it possible to increase the default vertical padding in input fields? It seems a bit cramped up.

To increase vertical padding please add _form-control-lg_ class to input.

**Comment by smolenski-mikolaj** [comment] 2020-07-07 10:36
Fixed in alpha-2 version.

**Closed as completed by smolenski-mikolaj** 2020-07-07 10:36 UTC
Labels: bug
